# games/CMakeLists.txt

# 1. Define Your Game Executable
# Rename "ProjectNebula" to your actual game title if you prefer
#add_executable(ProjectNebula 
   # "ProjectNebula/main.cpp"
    
    # As you add more files, list them here:
    # "ProjectNebula/Player.cpp"
    # "ProjectNebula/LevelLoader.cpp"
#)

# 2. Link the Engine
# This grants access to SFML, Box2D, Glad, and your shared utilities
#target_link_libraries(ProjectNebula PRIVATE Core)

# 3. IDE Organization
#set_target_properties(ProjectNebula PROPERTIES FOLDER "Games")